### ISSUE TITLE
MurderMystery Számláló bug

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#1014]
Pálya: Rémrom2

![image](https://user-images.githubusercontent.com/25465545/31894479-ddd12954-b80e-11e7-9bb4-cd1f1e17f3d3.png)
![image](https://user-images.githubusercontent.com/25465545/31894484-e38df084-b80e-11e7-9c19-3c1bf044fcb9.png)

**Comment by andris155** [comment]
Szinte biztos vagyok benne, hogy rosszul lett beállítva és az a baja.

**Comment by andris155** [comment]
```
[16:30:39] [Server thread/WARN]: [Murder] Task #5903139 for Murder v10.1 generated an exception
java.lang.IllegalArgumentException: Name cannot be null
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.12.2.jar:git-Paper-1233]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.getWorld(CraftServer.java:1077) ~[patched_1.12.2.jar:git-Paper-1233]
	at org.bukkit.Bukkit.getWorld(Bukkit.java:503) ~[patched_1.12.2.jar:git-Paper-1233]
	at me.joseph.murder.Main.getSpec(Main.java:492) ~[MurderMystery2.jar:?]
	at me.joseph.murder.Arena.start(Arena.java:957) ~[MurderMystery2.jar:?]
	at me.joseph.murder.Arena$1.run(Arena.java:190) ~[MurderMystery2.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.2.jar:git-Paper-1233]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [patched_1.12.2.jar:git-Paper-1233]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [patched_1.12.2.jar:git-Paper-1233]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1233]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1233]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1233]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```

**Comment by andris155** [comment]
Nincs beállítva a spectator rész elvileg.

**Comment by andris155** [comment]
```
[15:09:43] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to Murder v10.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1233]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1233]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1233]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) ~[patched_1.12.2.jar:git-Paper-1233]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) ~[patched_1.12.2.jar:git-Paper-1233]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) ~[patched_1.12.2.jar:git-Paper-1233]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:460) ~[patched_1.12.2.jar:git-Paper-1233]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:983) ~[patched_1.12.2.jar:git-Paper-1233]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[patched_1.12.2.jar:git-Paper-1233]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.12.2.jar:git-Paper-1233]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1233]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1233]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1233]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1233]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1233]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1233]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.IllegalArgumentException: Name cannot be null
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.12.2.jar:git-Paper-1233]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.getWorld(CraftServer.java:1077) ~[patched_1.12.2.jar:git-Paper-1233]
	at org.bukkit.Bukkit.getWorld(Bukkit.java:503) ~[patched_1.12.2.jar:git-Paper-1233]
	at me.joseph.murder.Main.getWait(Main.java:519) ~[MurderMystery2.jar:?]
	at me.joseph.murder.Arena.addPlayer(Arena.java:118) ~[MurderMystery2.jar:?]
	at me.joseph.murder.events.SignListener2.onSignInteract(SignListener2.java:86) ~[MurderMystery2.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor219.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1233]
	... 18 more
```

**Comment by andris155** [comment]
Itt meg az idő nincs beállítva

**Comment by andris155** [comment]
Mindent be kell állítani.
![kepkivagas](https://user-images.githubusercontent.com/8324198/31895212-dc2e3a2c-b810-11e7-9416-0a813d542943.PNG)

**Comment by andris155** [comment]
settime, settpectate ami kimaradt.

**Comment by andris155** [comment]
Köszönjük Hell!

**Comment by poma123** [comment]
![image](https://user-images.githubusercontent.com/25465545/31897344-5f27bc96-b816-11e7-8151-b274e6e53b70.png)
A "visszaszámlálás" nem fér ki a scoreboardon

**Comment by andris155** [comment]
nyiss újat erre
