### ISSUE TITLE
chatcontrol betöltési hiba

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#1408]
```
ERROR Could not load 'plugins/ChatControl.jar' in folder 'plugins'
10.01 21:39:25 [Server] INFO org.bukkit.plugin.InvalidPluginException: java.lang.ClassFormatError: Illegal UTF8 string in constant pool in class file me/kangarko/chatcontrol/ChatControl
10.01 21:39:25 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[patched_1.12.2.jar:git-Paper-1293]
10.01 21:39:25 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[patched_1.12.2.jar:git-Paper-1293]
10.01 21:39:25 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [patched_1.12.2.jar:git-Paper-1293]
10.01 21:39:25 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:306) [patched_1.12.2.jar:git-Paper-1293]
10.01 21:39:25 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:225) [patched_1.12.2.jar:git-Paper-1293]
10.01 21:39:25 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1293]
10.01 21:39:25 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
10.01 21:39:25 [Server] INFO Caused by: java.lang.ClassFormatError: Illegal UTF8 string in constant pool in class file me/kangarko/chatcontrol/ChatControl
10.01 21:39:25 [Server] INFO at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_151]
10.01 21:39:25 [Server] INFO at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_151]
10.01 21:39:25 [Server] INFO at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_151]
10.01 21:39:25 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:146) ~[patched_1.12.2.jar:git-Paper-1293]
10.01 21:39:25 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.12.2.jar:git-Paper-1293]
10.01 21:39:25 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
10.01 21:39:25 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
10.01 21:39:25 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:1.8.0_151]
10.01 21:39:25 [Server] INFO at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_151]
10.01 21:39:25 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82) ~[patched_1.12.2.jar:git-Paper-1293]
10.01 21:39:25 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.12.2.jar:git-Paper-1293]
10.01 21:39:25 [Server] INFO ... 6 more
```

**Comment by andris155** [comment]
A jegyzettömbel nem fog menni a konfigolás.

**Comment by poma123** [comment]
Notepad++-t használok.

**Comment by poma123** [comment]
Nem csak savszigeten nem tölt be. Amint volt az a restart a szervereken, az egyiken sincs betöltve.

![image](https://user-images.githubusercontent.com/25465545/34811486-62d7ae18-f6a1-11e7-9df7-153aad1408a9.png)

![image](https://user-images.githubusercontent.com/25465545/34811514-86418446-f6a1-11e7-8708-ff70e47b7baf.png)

![image](https://user-images.githubusercontent.com/25465545/34811525-978eb55c-f6a1-11e7-9cc8-bcc9945fad7b.png)

**Comment by andris155** [comment]
Nem tudom mi baja. Másnak sem igazán működik. Várok a fejlesztőre mit ír majd rá.

**Comment by poma123** [comment]
Végül sikerült?

**Comment by Sheep04** [comment]
Láthatólag igen.
