### ISSUE TITLE
SavSziget OreGen hiba

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#1787]
```
02.02 20:08:13 [Server] ERROR Could not pass event BlockFormEvent to CustomOreGen v1.2.34
02.02 20:08:13 [Server] INFO org.bukkit.event.EventException: null
02.02 20:08:13 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1313]
02.02 20:08:13 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.2.jar:git-Paper-1313]
02.02 20:08:13 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1313]
02.02 20:08:13 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) [patched_1.12.2.jar:git-Paper-1313]
02.02 20:08:13 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) [patched_1.12.2.jar:git-Paper-1313]
02.02 20:08:13 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleBlockFormEvent(CraftEventFactory.java:1113) [patched_1.12.2.jar:git-Paper-1313]
02.02 20:08:13 [Server] INFO at net.minecraft.server.v1_12_R1.BlockFlowing.b(BlockFlowing.java:110) [patched_1.12.2.jar:git-Paper-1313]
02.02 20:08:13 [Server] INFO at net.minecraft.server.v1_12_R1.WorldServer.a(WorldServer.java:786) [patched_1.12.2.jar:git-Paper-1313]
02.02 20:08:13 [Server] INFO at net.minecraft.server.v1_12_R1.WorldServer.doTick(WorldServer.java:317) [patched_1.12.2.jar:git-Paper-1313]
02.02 20:08:13 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:897) [patched_1.12.2.jar:git-Paper-1313]
02.02 20:08:13 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1313]
02.02 20:08:13 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1313]
02.02 20:08:13 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1313]
02.02 20:08:13 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
02.02 20:08:13 [Server] INFO Caused by: java.lang.IllegalArgumentException: UUID cannot be null
02.02 20:08:13 [Server] INFO at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.12.2.jar:git-Paper-1313]
02.02 20:08:13 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.getOfflinePlayer(CraftServer.java:1374) ~[patched_1.12.2.jar:git-Paper-1313]
02.02 20:08:13 [Server] INFO at org.bukkit.Bukkit.getOfflinePlayer(Bukkit.java:747) ~[patched_1.12.2.jar:git-Paper-1313]
02.02 20:08:13 [Server] INFO at de.Linus122.customoregen.Main.getOwner(Main.java:103) ~[CustomOreGen.jar:?]
02.02 20:08:13 [Server] INFO at de.Linus122.customoregen.Events.onCobbleGen(Events.java:29) ~[CustomOreGen.jar:?]
02.02 20:08:13 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor23.execute(Unknown Source) ~[?:?]
02.02 20:08:13 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1313]
02.02 20:08:13 [Server] INFO ... 13 more
```

**Comment by andris155** [comment]
A vízfolyás-nak nincs UUID-je. Így null értéket kér le.

**Comment by andris155** [comment]
Jelentve a fejlesztőnek.
