### ISSUE TITLE
YoutubeBridge ,,View Youtubers gomb" hiba

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#1809]
```
06.02 17:47:41 [Server] ERROR Could not pass event InventoryClickEvent to YouTubeBridge v2.0.7_1
06.02 17:47:41 [Server] INFO java.lang.StackOverflowError: null
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
06.02 17:47:41 [Server] INFO at me.TechXcrafter.ytIsNice.uuidfetcher.UUIDStorage.getAllDataSets(UUIDStorage.java:51) ~[YouTubeBridge.jar:?]
```

**Comment by andris155** [comment]
Javítva
