### ISSUE TITLE
Savsziget,nem működik az érc generátor.

### ISSUE THREAD

**Issue by Dreed1992** [andris155/TheOld-Crafters#1851]
Reggel óta nem működik az érc generátor.A hibát több játékos is jelezte,én is próbáltam.

-Agronaut

**Comment by poma123** [comment]
```
23.02 08:42:04 [Server] ERROR Error occurred while enabling CustomOreGen v1.2.37 (Is it up to date?)
23.02 08:42:04 [Server] INFO java.lang.Error: Unresolved compilation problem: 
23.02 08:42:04 [Server] INFO The declared package "de.Linus122.SpaceIOMetrics" does not match the expected package "de.Linus122.customoregen"
23.02 08:42:04 [Server] INFO at de.Linus122.customoregen.Metrics.<init>(Metrics.java:1) ~[?:?]
23.02 08:42:04 [Server] INFO at de.Linus122.customoregen.Main.onEnable(Main.java:64) ~[?:?]
23.02 08:42:04 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1331]
23.02 08:42:04 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.2.jar:git-Paper-1331]
23.02 08:42:04 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [patched_1.12.2.jar:git-Paper-1331]
23.02 08:42:04 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:387) [patched_1.12.2.jar:git-Paper-1331]
23.02 08:42:04 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:336) [patched_1.12.2.jar:git-Paper-1331]
23.02 08:42:04 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1331]
23.02 08:42:04 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1331]
23.02 08:42:04 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1331]
23.02 08:42:04 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292) [patched_1.12.2.jar:git-Paper-1331]
23.02 08:42:04 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1331]
23.02 08:42:04 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
23.02 08:42:04 [Server] INFO Disabling CustomOreGen v1.2.37

```

**Comment by poma123** [comment]
Javítva!
Köszönjük a hibajelentést!
