### ISSUE TITLE
mcMMO ConcurrentModificationException

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#2029]
```
11.05 15:01:58 [Server] WARN Task #23 for mcMMO v1.5.09-SNAPSHOT generated an exception
11.05 15:01:58 [Server] INFO java.util.ConcurrentModificationException: null
11.05 15:01:58 [Server] INFO at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442) ~[?:1.8.0_161]
11.05 15:01:58 [Server] INFO at java.util.HashMap$EntryIterator.next(HashMap.java:1476) ~[?:1.8.0_161]
11.05 15:01:58 [Server] INFO at java.util.HashMap$EntryIterator.next(HashMap.java:1474) ~[?:1.8.0_161]
11.05 15:01:58 [Server] INFO at com.gmail.nossr50.runnables.skills.BleedTimerTask.run(BleedTimerTask.java:24) ~[mcMMO.jar:?]
11.05 15:01:58 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1414]
11.05 15:01:58 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) [patched_1.12.2.jar:git-Paper-1414]
11.05 15:01:58 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [patched_1.12.2.jar:git-Paper-1414]
11.05 15:01:58 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1414]
11.05 15:01:58 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1414]
11.05 15:01:58 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1414]
11.05 15:01:58 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

11.05 15:02:00 [Server] WARN Task #23 for mcMMO v1.5.09-SNAPSHOT generated an exception
11.05 15:02:00 [Server] INFO java.util.ConcurrentModificationException: null
11.05 15:02:00 [Server] INFO at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442) ~[?:1.8.0_161]
11.05 15:02:00 [Server] INFO at java.util.HashMap$EntryIterator.next(HashMap.java:1476) ~[?:1.8.0_161]
11.05 15:02:00 [Server] INFO at java.util.HashMap$EntryIterator.next(HashMap.java:1474) ~[?:1.8.0_161]
11.05 15:02:00 [Server] INFO at com.gmail.nossr50.runnables.skills.BleedTimerTask.run(BleedTimerTask.java:24) ~[mcMMO.jar:?]
11.05 15:02:00 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1414]
11.05 15:02:00 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) [patched_1.12.2.jar:git-Paper-1414]
11.05 15:02:00 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [patched_1.12.2.jar:git-Paper-1414]
11.05 15:02:00 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1414]
11.05 15:02:00 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1414]
11.05 15:02:00 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1414]
11.05 15:02:00 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```

**Comment by andris155** [comment]
Már jelentett hiba.
