### ISSUE TITLE
Could not pass event InventoryClickEvent to EnderContainers v2.1.0

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#2136]
```
04.07 21:05:50 [Server] ERROR Could not pass event InventoryClickEvent to EnderContainers v2.1.0
04.07 21:05:50 [Server] INFO org.bukkit.event.EventException: null
04.07 21:05:50 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1468]
04.07 21:05:50 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1468]
04.07 21:05:50 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1468]
04.07 21:05:50 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[patched_1.12.2.jar:git-Paper-1468]
04.07 21:05:50 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[patched_1.12.2.jar:git-Paper-1468]
04.07 21:05:50 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1981) ~[patched_1.12.2.jar:git-Paper-1468]
04.07 21:05:50 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.12.2.jar:git-Paper-1468]
04.07 21:05:50 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.12.2.jar:git-Paper-1468]
04.07 21:05:50 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1468]
04.07 21:05:50 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
04.07 21:05:50 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
04.07 21:05:50 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1468]
04.07 21:05:50 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1468]
04.07 21:05:50 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1468]
04.07 21:05:50 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1468]
04.07 21:05:50 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1468]
04.07 21:05:50 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
04.07 21:05:50 [Server] INFO Caused by: java.util.ConcurrentModificationException
04.07 21:05:50 [Server] INFO at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442) ~[?:1.8.0_171]
04.07 21:05:50 [Server] INFO at java.util.HashMap$KeyIterator.next(HashMap.java:1466) ~[?:1.8.0_171]
04.07 21:05:50 [Server] INFO at fr.utarwyn.endercontainers.menu.Menus.getMenuFromInventory(Menus.java:91) ~[EnderContainers-2.1.0.jar:?]
04.07 21:05:50 [Server] INFO at fr.utarwyn.endercontainers.menu.Menus.onInventoryClick(Menus.java:58) ~[EnderContainers-2.1.0.jar:?]
04.07 21:05:50 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor925.execute(Unknown Source) ~[?:?]
04.07 21:05:50 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1468]
04.07 21:05:50 [Server] INFO ... 16 more
```

**Comment by andris155** [comment]
Ezekkel én foglalkozom. Neked nem kell. :)

**Comment by poma123** [comment]
:)
