### ISSUE TITLE
/ocd egyenleg

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2158]
Ha beírjuk a /ocd egyenleg parancsot:
![2018-07-18_13 14 43](https://user-images.githubusercontent.com/29951969/42878299-d3c211ac-8a8c-11e8-9971-792aee2c5fe8.png)

**Comment by skrisz0101** [comment]
utolsó előtti sor

**Comment by poma123** [comment]
![image](https://user-images.githubusercontent.com/25465545/42888032-98600856-8aa7-11e8-8a5b-457994eb29c2.png)
```
18.07 16:29:03 [Server] INFO poma123 issued server command: /ocd egyenleg
18.07 16:29:03 [Server] WARN hu.infinityhosting.MineMarketAPI.Exceptions.NoResponseException: Az API szerver nem válaszol
18.07 16:29:03 [Server] WARN at hu.infinityhosting.MineMarketAPI.MMAPI.getXML(MMAPI.java:120)
18.07 16:29:03 [Server] WARN at hu.infinityhosting.MineMarketAPI.MMAPI.getUserCredit(MMAPI.java:397)
18.07 16:29:03 [Server] WARN at hu.Bod.Kredites.Kredites.onCommand(Kredites.java:96)
18.07 16:29:03 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
18.07 16:29:03 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
18.07 16:29:03 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
18.07 16:29:03 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1472)
18.07 16:29:03 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1277)
18.07 16:29:03 [Server] WARN at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
18.07 16:29:03 [Server] WARN at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
18.07 16:29:03 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
18.07 16:29:03 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
18.07 16:29:03 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
18.07 16:29:03 [Server] WARN at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
18.07 16:29:03 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843)
18.07 16:29:03 [Server] WARN at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427)
18.07 16:29:03 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
18.07 16:29:03 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
18.07 16:29:03 [Server] WARN at java.lang.Thread.run(Thread.java:748)
```

**Comment by andris155** [comment]
Az SSL meglett újítva
