### ISSUE TITLE
iZone vs. snowman trail

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#230]
```
[02:37:31] [Server thread/ERROR]: Could not pass event EntityBlockFormEvent to iZone v7.6.5
org.bukkit.event.EventException
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.10.jar:git-Paper-792]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.10.jar:git-Paper-792]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.10.jar:git-Paper-792]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.10.jar:git-Paper-792]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.10.jar:git-Paper-792]
	at net.minecraft.server.v1_10_R1.EntitySnowman.n(EntitySnowman.java:73) [patched_1.10.jar:git-Paper-792]
	at net.minecraft.server.v1_10_R1.EntityLiving.m(EntityLiving.java:1840) [patched_1.10.jar:git-Paper-792]
	at net.minecraft.server.v1_10_R1.EntityInsentient.m(EntityInsentient.java:241) [patched_1.10.jar:git-Paper-792]
	at net.minecraft.server.v1_10_R1.World.entityJoinedWorld(World.java:1721) [patched_1.10.jar:git-Paper-792]
	at net.minecraft.server.v1_10_R1.World.g(World.java:1696) [patched_1.10.jar:git-Paper-792]
	at net.minecraft.server.v1_10_R1.World.tickEntities(World.java:1520) [patched_1.10.jar:git-Paper-792]
	at net.minecraft.server.v1_10_R1.WorldServer.tickEntities(WorldServer.java:635) [patched_1.10.jar:git-Paper-792]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:865) [patched_1.10.jar:git-Paper-792]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.10.jar:git-Paper-792]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:730) [patched_1.10.jar:git-Paper-792]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:629) [patched_1.10.jar:git-Paper-792]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_10_R1.entity.CraftSnowman cannot be cast to org.bukkit.entity.Player
	at net.techguard.izone.listeners.eListener.onEntityBlockFormEvent(eListener.java:292) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor798.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.10.jar:git-Paper-792]
	... 16 more
```

**Comment by andris155** [comment]
@EventHandler(ignoreCancelled = true)

**Comment by andris155** [comment]
if(e instanceof Player)
javítva.
