### ISSUE TITLE
OpenInv

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#2553]
```
03.12 19:53:06 [Server] INFO baumannkitti issued server command: /oi Keati
03.12 19:53:06 [Server] WARN java.lang.IllegalAccessException: Can not set final net.minecraft.server.v1_13_R2.NonNullList field net.minecraft.server.v1_13_R2.PlayerInventory.items to net.minecraft.server.v1_13_R2.NonNullList
03.12 19:53:06 [Server] WARN at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:76)
03.12 19:53:06 [Server] WARN at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:80)
03.12 19:53:06 [Server] WARN at java.base/jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.set(UnsafeQualifiedObjectFieldAccessorImpl.java:79)
03.12 19:53:06 [Server] WARN at java.base/java.lang.reflect.Field.set(Field.java:780)
03.12 19:53:06 [Server] WARN at com.lishid.openinv.internal.v1_13_R2.SpecialPlayerInventory.setItemArrays(SpecialPlayerInventory.java:161)
03.12 19:53:06 [Server] WARN at com.lishid.openinv.internal.v1_13_R2.SpecialPlayerInventory.<init>(SpecialPlayerInventory.java:43)
03.12 19:53:06 [Server] WARN at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
03.12 19:53:06 [Server] WARN at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
03.12 19:53:06 [Server] WARN at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
03.12 19:53:06 [Server] WARN at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
03.12 19:53:06 [Server] WARN at com.lishid.openinv.util.InternalAccessor.createObject(InternalAccessor.java:103)
03.12 19:53:06 [Server] WARN at com.lishid.openinv.util.InternalAccessor.newSpecialPlayerInventory(InternalAccessor.java:210)
03.12 19:53:06 [Server] WARN at com.lishid.openinv.OpenInv.getSpecialInventory(OpenInv.java:327)
03.12 19:53:06 [Server] WARN at com.lishid.openinv.commands.OpenInvPluginCommand.openInventory(OpenInvPluginCommand.java:148)
03.12 19:53:06 [Server] WARN at com.lishid.openinv.commands.OpenInvPluginCommand.access$100(OpenInvPluginCommand.java:33)
03.12 19:53:06 [Server] WARN at com.lishid.openinv.commands.OpenInvPluginCommand$1$1.run(OpenInvPluginCommand.java:89)
03.12 19:53:06 [Server] WARN at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82)
03.12 19:53:06 [Server] WARN at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:448)
03.12 19:53:06 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008)
03.12 19:53:06 [Server] WARN at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
03.12 19:53:06 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943)
03.12 19:53:06 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841)
03.12 19:53:06 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by andris155** [comment]
https://github.com/lishid/OpenInv/issues

**Comment by andris155** [comment]
https://github.com/lishid/OpenInv/issues/93

**Comment by andris155** [comment]
javítva
