### ISSUE TITLE
Craftbook hibák

### ISSUE THREAD

**Issue by SurvivorTheReal** [andris155/TheOld-Crafters#2937]
Megy a pipe, köszönjük, de van még egy kis hiba, tényleg kicsi. Csak tölgyfa táblával engedi feltáblázni többivel nem. Tényleg kis hiba, és sztem el is hanyagolható, de huntival arra jutottunk, hogy azért valamelyikünk ír githubra.

**Comment by andris155** [comment]
Nem egyszerű ezzel kapcsolatban a plugin-al hibát jelenteni. Kérlek szedjétek össze az összes dolgot és akkor egyben megírom a hibákat a fejlesztőnek. Úgy halottam valami fejek sem működnek vele.

**Comment by Huntermaster0** [comment]
Még egy régebbi farmom építésekor jött elő a következő hiba: Adott egy hopper alatta egy pistonnal, ami Pipenak van bekötve. Ha a hopperből comparatorral ki akarom szedni a jelet, akkor az csak bugosan megy. A comparator valahogyan jelet ad a pistonnak (ez kb. lehetetlen lenne), ami így kiszívja az itemet a tölcsérből. Ez még jó is lenne (bár szerintem már alapból bug), hisz akkor instant meg lehetne oldani az elszívást. Viszont miután elszívta a piston a cuccot, azután a comparator még jelet ad, és úgy érzékeli, hogy van item a hopperben (miközben az üres). Később csatolok képet, ha kell hozzá.

**Comment by andris155** [comment]
```
[00:13:28] [Server thread/ERROR]: Could not pass event SourcedBlockRedstoneEvent to CraftBook v3.10-SNAPSHOT;4505-8c25911
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217) ~[patched_1.14.2.jar:git-Paper-55]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[patched_1.14.2.jar:git-Paper-55]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[patched_1.14.2.jar:git-Paper-55]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[patched_1.14.2.jar:git-Paper-55]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) ~[patched_1.14.2.jar:git-Paper-55]
	at com.sk89q.craftbook.util.ItemSyntax.getItem(ItemSyntax.java:289) ~[?:?]
	at com.sk89q.craftbook.mechanics.pipe.Pipes.searchNearbyPipes(Pipes.java:224) ~[?:?]
	at com.sk89q.craftbook.mechanics.pipe.Pipes.searchNearbyPipes(Pipes.java:206) ~[?:?]
	at com.sk89q.craftbook.mechanics.pipe.Pipes.searchNearbyPipes(Pipes.java:206) ~[?:?]
	at com.sk89q.craftbook.mechanics.pipe.Pipes.searchNearbyPipes(Pipes.java:206) ~[?:?]
	at com.sk89q.craftbook.mechanics.pipe.Pipes.startPipe(Pipes.java:393) ~[?:?]
	at com.sk89q.craftbook.mechanics.pipe.Pipes.onBlockRedstoneChange(Pipes.java:494) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor907.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.2.jar:git-Paper-55]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.2.jar:git-Paper-55]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.2.jar:git-Paper-55]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:534) ~[patched_1.14.2.jar:git-Paper-55]
	at com.sk89q.craftbook.bukkit.MechanicListenerAdapter.handleDirectWireInput(MechanicListenerAdapter.java:345) ~[?:?]
	at com.sk89q.craftbook.bukkit.MechanicListenerAdapter.handleRedstoneForBlock(MechanicListenerAdapter.java:281) ~[?:?]
	at com.sk89q.craftbook.bukkit.MechanicListenerAdapter.onBlockRedstoneChange(MechanicListenerAdapter.java:184) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.14.2.jar:git-Paper-55]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.2.jar:git-Paper-55]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.2.jar:git-Paper-55]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:534) ~[patched_1.14.2.jar:git-Paper-55]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callRedstoneChange(CraftEventFactory.java:1243) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.BlockRedstoneComparator.f(BlockRedstoneComparator.java:133) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.BlockRedstoneComparator.tick(BlockRedstoneComparator.java:147) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.IBlockData.a(IBlockData.java:201) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.WorldServer.b(WorldServer.java:553) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.TickListServer.a(TickListServer.java:90) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:268) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1177) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.2.jar:git-Paper-55]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.2.jar:git-Paper-55]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[patched_1.14.2.jar:git-Paper-55]
	at com.sk89q.worldedit.blocks.BaseItem.<init>(BaseItem.java:48) ~[?:?]
	at com.sk89q.worldedit.extension.factory.parser.DefaultItemParser.parseFromInput(DefaultItemParser.java:52) ~[?:?]
	at com.sk89q.worldedit.extension.factory.parser.DefaultItemParser.parseFromInput(DefaultItemParser.java:33) ~[?:?]
	at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:69) ~[?:?]
	at com.sk89q.craftbook.util.ItemSyntax$1.load(ItemSyntax.java:150) ~[?:?]
	at com.sk89q.craftbook.util.ItemSyntax$1.load(ItemSyntax.java:137) ~[?:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[patched_1.14.2.jar:git-Paper-55]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[patched_1.14.2.jar:git-Paper-55]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[patched_1.14.2.jar:git-Paper-55]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[patched_1.14.2.jar:git-Paper-55]
	... 341 more
```

**Comment by andris155** [comment]
A táblás már jelentett hiba:
(Végre működik a saját hibajelentője. Eddig le volt tiltva...)
https://dev.enginehub.org/youtrack/issue/CRAFTBOOK-3432

**Comment by SurvivorTheReal** [comment]
Oké, ömm, én nem tapasztaltam más hibát már ezen kivül, hunti a megtalálója ezeknek. Az én agyam addig jut el hogy viszi vagy nem, és hogy megvan-e az item a másik ládában.

**Comment by Huntermaster0** [comment]
Volt ugye a másik hiba, fejet nem visz. Hiába ugyanaz, mint /iteminfo-nál. Ha minden igaz szóköz helyére _ kell, így a Player_Head#6o (ami a pigman egyik fajta feje) nem szállítható valamilyen oknál fogva. Megoldás persze van rá, de szerintem van olyan helyzet, amikor nem megoldható még így sem a szállítása. 1 órája találtam rá, hogy a 4. sorba írhatóak azok az itemek, akiket a Pipe ne szelektáljon.

**Comment by andris155** [comment]
Ha csak simán PLAYER_HEAD-nek írod az sem jó? A Chestshop #6o részt csak a Chestshop támogatja.

**Comment by andris155** [comment]
Innen érdemes lenézni a tárgyneveket:
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

**Comment by Huntermaster0** [comment]
Player_Head (szerintem így is jónak kell lennie) nem megy.

**Comment by andris155** [comment]
Tudsz képest küldeni, hogy hogyan van a táblára írva? A fejlesztő talán könnyebben megérti képpel.

**Comment by Frenzy79** [comment]
Az Én rendszerem csak félig működik! Az első 434 ládába berakja az itemeket de utána már nem és a legnagyobb baj az hogy eltűnnek az éterben. így elég sokmindent elvesztettem, mire észrevettem.
