### ISSUE TITLE
Új verziós Chestshop hiba elemzése és javítása Savsziget

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#2958]
```
[13:11:21] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'Spawn'
[13:11:21] [Server thread/ERROR]: Error occurred while enabling WorldGuard v7.0.0-beta-03;e51a220 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at com.sk89q.worldguard.protection.flags.registry.SimpleFlagRegistry.unmarshal(SimpleFlagRegistry.java:127) ~[?:?]
	at com.sk89q.worldguard.protection.managers.storage.file.YamlRegionFile.setFlags(YamlRegionFile.java:295) ~[?:?]
	at com.sk89q.worldguard.protection.managers.storage.file.YamlRegionFile.loadAll(YamlRegionFile.java:166) ~[?:?]
	at com.sk89q.worldguard.protection.managers.RegionManager.load(RegionManager.java:101) ~[?:?]
	at com.sk89q.worldguard.protection.managers.RegionContainerImpl.createAndLoad(RegionContainerImpl.java:129) ~[?:?]
	at com.sk89q.worldguard.protection.managers.RegionContainerImpl.load(RegionContainerImpl.java:106) ~[?:?]
	at com.sk89q.worldguard.bukkit.BukkitRegionContainer.load(BukkitRegionContainer.java:113) ~[?:?]
	at com.sk89q.worldguard.protection.regions.RegionContainer.loadWorlds(RegionContainer.java:174) ~[?:?]
	at com.sk89q.worldguard.protection.regions.RegionContainer.initialize(RegionContainer.java:64) ~[?:?]
	at com.sk89q.worldguard.bukkit.BukkitRegionContainer.initialize(BukkitRegionContainer.java:66) ~[?:?]
	at com.sk89q.worldguard.bukkit.BukkitWorldGuardPlatform.load(BukkitWorldGuardPlatform.java:110) ~[?:?]
	at com.sk89q.worldguard.WorldGuard.setup(WorldGuard.java:97) ~[?:?]
	at com.sk89q.worldguard.bukkit.WorldGuardPlugin.onEnable(WorldGuardPlugin.java:135) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.13.2.jar:git-Paper-630]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[patched_1.13.2.jar:git-Paper-630]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) ~[patched_1.13.2.jar:git-Paper-630]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-630]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-630]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-630]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-630]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-630]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-630]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-630]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: com.sk89q.worldguard.protection.flags.registry.FlagConflictException: A flag already exists by the name allow-shop
	at com.sk89q.worldguard.protection.flags.registry.SimpleFlagRegistry.forceRegister(SimpleFlagRegistry.java:88) ~[?:?]
	at com.sk89q.worldguard.protection.flags.registry.SimpleFlagRegistry.register(SimpleFlagRegistry.java:64) ~[?:?]
	at com.sk89q.worldguard.protection.flags.Flags.register(Flags.java:157) ~[?:?]
	at com.sk89q.worldguard.protection.flags.Flags.<clinit>(Flags.java:147) ~[?:?]
	... 24 more
[13:11:21] [Server thread/INFO]: [WorldGuard] Disabling WorldGuard v7.0.0-beta-03;e51a220
[13:11:21] [Server thread/INFO]: [WorldGuard] Shutting down executor and waiting for any pending tasks...
```

**Comment by andris155** [comment]
A régi WorldGaurd-al nem megy. Egyelőre jó a régebbi verzió is.
