### ISSUE TITLE
Bújócska 

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3168]
Nem jó a bújócska, nem lehet csatlakozni, mivel nincs aréna, pedig 2 napja mikor teszteltük, minden jó volt. Nem lehet hogy akkor lett törölve valami, amikor a statisztikák is?

![kép](https://user-images.githubusercontent.com/29709854/62851326-04c48a00-bce6-11e9-8fa7-3135bb984bc6.png)

**Comment by andris155** [comment]
```
[00:16:29] [Server thread/WARN]: [HideAndSeek] Task #56 for HideAndSeek v3.3 generated an exception
java.lang.NullPointerException: null
	at me.wazup.hideandseek.HideAndSeek$3.run(HideAndSeek.java:1084) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-167]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1147) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[patched_1.14.4.jar:git-Paper-167]
	at java.lang.Thread.run(Unknown Source) [?:?]
```
A táblák adatbázisával van valami gond.
Holnap ha betölt elvileg jó lesz, de a táblákat újra be kell állítani.
Talán lehet köztük valami törölt aréna?
```
Signs:
  Join:
    Teveváros: survivalgames, -2742, 24, 1393
    Nether: survivalgames, -2742, 24, 1394
    Horror: survivalgames, -2742, 24, 1395
    Sivatagifalu: survivalgames, -2742, 24, 1397
    Vég: survivalgames, -2742, 24, 1399
    Aréna1: survivalgames, -2728, 25, 1408
    Aréna2: survivalgames, -2729, 25, 1408
    Aréna3: survivalgames, -2730, 25, 1408
    Rémálom: survivalgames, -2742, 24, 1398
    Normandia: survivalgames, -2742, 25, 1399
    Aréna4: survivalgames, -2731, 25, 1408
    Sivatag: survivalgames, -2742, 25, 1394
    Vízivilág: survivalgames, -2742, 25, 1393
    Konténer: survivalgames, -2742, 26, 1399
    DNS: survivalgames, -2742, 25, 1397
    Sziget: survivalgames, -2742, 25, 1396
    Rét: survivalgames, -2742, 25, 1395
    Aréna5: survivalgames, -2732, 25, 1408
    Csatorna: survivalgames, -2742, 24, 1396
    Arena6: survivalgames, -2728, 24, 1408
    Japánfalu: survivalgames, -2742, 26, 1398
    Repülő: survivalgames, -2742, 25, 1398
  Top:
    '1':
      world: survivalgames
      x: -2718.0
      y: 25.0
      z: 1396.0
    '2':
      world: survivalgames
      x: -2719.0
      y: 24.0
      z: 1395.0
    '3':
      world: survivalgames
      x: -2719.0
      y: 23.0
      z: 1397.0
```

**Comment by poma123** [comment]
vagy ahol nincs fizikailag tábla, de a konfig tartalmazza

**Comment by andris155** [comment]
Továbbra is hibát ír. Nem tudom mi baja van.

**Comment by poma123** [comment]
próbáltam rájönni de fogalmam nincs

**Comment by andris155** [comment]
Elvileg már jó.
1 óra alatt sikerült rájönni, hogy igazából az 1.14-es blokkokat nem támogatja. Ezeket kikerestem és kiszedtem. A hibaüzenet eltűnt.
Ezeket kellet kiszednem:
- RED_NETHER_BRICK_STAIRS
- MOSSY_STONE_BRICK_STAIRS
- FLETCHING_TABLE
- COMPOSTER
Ameddig nem támogatja az 1.14-es blokkokat, addig ne használjátok mert konkrétan magát teszi tönkre így.
