### ISSUE TITLE
Savsziget - Team invite hiba

### ISSUE THREAD

**Issue by Feketeblue** [andris155/TheOld-Crafters#3283]
Savszigeten már elég sok játékos bajlódik azzal hogy a barátjait hogyan invitálja meg a szigetére. Valamiért a(z) /is team invite -név- nem működik, és ha a játékos elfogadja és /is-t ír be, spectatorba dobja. Lehetne csinálni vele valamit, mert szerintem nem a legjobb /is settings-be beállítani mindent a coop rangú játékosnak, aztán /is team coop-olni az embert. Ma már történt egy ilyen eset, amin az illető kiakadt, és kicsit kritizálta a szervert + a neki segítő 2playert.
(Verzió amiben játszok: 1.14.4)

**Comment by poma123** [comment]
```
[10:53:32 WARN]: [BentoBox] Task #506895 for BentoBox v1.9.0-SNAPSHOT-b1437 generated an exception
java.lang.AbstractMethodError: Receiver class world.bentobox.acidisland.AISettings does not define or inherit an implementation of the resolved method 'abstract boolean isOnJoinResetHealth()' of interface world.bentobox.bentobox.api.configuration.WorldSettings.
at world.bentobox.bentobox.managers.IslandWorldManager.isOnJoinResetHealth(IslandWorldManager.java:538) ~[?:?]
at world.bentobox.bentobox.api.commands.island.team.IslandTeamInviteAcceptCommand.cleanPlayer(IslandTeamInviteAcceptCommand.java:175) ~[?:?]
at world.bentobox.bentobox.api.commands.island.team.IslandTeamInviteAcceptCommand.acceptTeamInvite(IslandTeamInviteAcceptCommand.java:130) ~[?:?]
at world.bentobox.bentobox.api.commands.island.team.IslandTeamInviteAcceptCommand.lambda$execute$2(IslandTeamInviteAcceptCommand.java:85) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-221]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-221]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) ~[patched_1.14.4.jar:git-Paper-221]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-221]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-221]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-221]
at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by Feketeblue** [comment]
Köszi! :D

**Comment by poma123** [comment]
BentoboxWorld/BentoBox#1015

**Comment by poma123** [comment]
Javítva!
