### ISSUE TITLE
Savsziget - eventtopten parancs

### ISSUE THREAD

**Issue by Niccolettie** [andris155/TheOld-Crafters#3479]
Savszigeten szerveren senkinek nem működik a /eventtopten sem a /eventtoptiz és a /eventtoptíz sem.
_An internal error occurred while attempting to perform this command_

**Comment by andris155** [comment]
```
[10:01:44] [Server thread/INFO]: [EventRendszer] Enabling EventRendszer v1.0
[10:01:44] [Server thread/ERROR]: Error occurred while enabling EventRendszer v1.0 (Is it up to date?)
java.lang.StackOverflowError: null
	at java.lang.StringBuilder.<init>(Unknown Source) ~[?:?]
	at org.yaml.snakeyaml.nodes.MappingNode.toString(MappingNode.java:103) ~[patched_1.15.2.jar:git-Paper-149]
	at java.lang.String.valueOf(Unknown Source) ~[?:?]
	at java.lang.StringBuilder.append(Unknown Source) ~[?:?]
	at org.yaml.snakeyaml.nodes.MappingNode.toString(MappingNode.java:106) ~[patched_1.15.2.jar:git-Paper-149]
	at java.lang.String.valueOf(Unknown Source) ~[?:?]
	at java.lang.StringBuilder.append(Unknown Source) ~[?:?]
	at org.yaml.snakeyaml.nodes.MappingNode.toString(MappingNode.java:106) ~[patched_1.15.2.jar:git-Paper-149]
	at java.lang.String.valueOf(Unknown Source) ~[?:?]
	at java.lang.StringBuilder.append(Unknown Source) ~[?:?]
	at org.yaml.snakeyaml.nodes.MappingNode.toString(MappingNode.java:106) ~[patched_1.15.2.jar:git-Paper-149]
	at java.lang.String.valueOf(Unknown Source) ~[?:?]
	at java.lang.StringBuilder.append(Unknown Source) ~[?:?]
	at org.yaml.snakeyaml.nodes.MappingNode.toString(MappingNode.java:106) ~[patched_1.15.2.jar:git-Paper-149]
	at java.lang.String.valueOf(Unknown Source) ~[?:?]
	at java.lang.StringBuilder.append(Unknown Source) ~[?:?]
	at org.yaml.snakeyaml.nodes.MappingNode.toString(MappingNode.java:106) ~[patched_1.15.2.jar:git-Paper-149]
	at java.lang.String.valueOf(Unknown Source) ~[?:?]
	at java.lang.StringBuilder.append(Unknown Source) ~[?:?]
	at org.yaml.snakeyaml.nodes.MappingNode.toString(MappingNode.java:106) ~[patched_1.15.2.jar:git-Paper-149]
	at java.lang.String.valueOf(Unknown Source) ~[?:?]
	at java.lang.StringBuilder.append(Unknown Source) ~[?:?]
	at org.yaml.snakeyaml.nodes.MappingNode.toString(MappingNode.java:106) ~[patched_1.15.2.jar:git-Paper-149]
	at java.lang.String.valueOf(Unknown Source) ~[?:?]
	at java.lang.StringBuilder.append(Unknown Source) ~[?:?]
	at org.yaml.snakeyaml.nodes.MappingNode.toString(MappingNode.java:106) ~[patched_1.15.2.jar:git-Paper-149]
	at java.lang.String.valueOf(Unknown Source) ~[?:?]
	at java.lang.StringBuilder.append(Unknown Source) ~[?:?]
	at org.yaml.snakeyaml.nodes.MappingNode.toString(MappingNode.java:106) ~[patched_1.15.2.jar:git-Paper-149]
	at java.lang.String.valueOf(Unknown Source) ~[?:?]
	at java.lang.StringBuilder.append(Unknown Source) ~[?:?]
	at org.yaml.snakeyaml.nodes.MappingNode.toString(MappingNode.java:106) ~[patched_1.15.2.jar:git-Paper-149]
	at java.lang.String.valueOf(Unknown Source) ~[?:?]
	at java.lang.StringBuilder.append(Unknown Source) ~[?:?]
	at org.yaml.snakeyaml.nodes.MappingNode.toString(MappingNode.java:106) ~[patched_1.15.2.jar:git-Paper-149]
	at java.lang.String.valueOf(Unknown Source) ~[?:?]
```
