### ISSUE TITLE
SG szavazás hiba

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#40]
19:22:57] [Server thread/WARN]: [SurvivalGames] Task #2710456 for SurvivalGames vBeta dev1.9.4b generated an exception
java.lang.NoSuchMethodError: me.maker56.survivalgames.game.Game.sendMessage(Lme/maker56/survivalgames/chat/JSONMessage;)V
	at me.maker56.survivalgames.game.phases.VotingPhase.sendVoteMessage(VotingPhase.java:244) ~[?:?]
	at me.maker56.survivalgames.game.phases.VotingPhase.access$2(VotingPhase.java:236) ~[?:?]
	at me.maker56.survivalgames.game.phases.VotingPhase$1.run(VotingPhase.java:97) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[spigot_1.8.jar:git-PaperSpigot-a26fef5-07c3001]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [spigot_1.8.jar:git-PaperSpigot-a26fef5-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:781) [spigot_1.8.jar:git-PaperSpigot-a26fef5-07c3001]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot_1.8.jar:git-PaperSpigot-a26fef5-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [spigot_1.8.jar:git-PaperSpigot-a26fef5-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [spigot_1.8.jar:git-PaperSpigot-a26fef5-07c3001]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]
[19:22:58] [Server thread/WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.ChatSerializer
[19:22:58] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92)
[19:22:58] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87)
[19:22:58] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[19:22:58] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[19:22:58] [Server thread/WARN]: 	at java.lang.Class.forName0(Native Method)
[19:22:58] [Server thread/WARN]: 	at java.lang.Class.forName(Unknown Source)
[19:22:58] [Server thread/WARN]: 	at me.maker56.survivalgames.chat.ReflectionUtil.getNMSClass(ReflectionUtil.java:43)
[19:22:58] [Server thread/WARN]: 	at me.maker56.survivalgames.chat.JSONMessage.<init>(JSONMessage.java:51)
[19:22:58] [Server thread/WARN]: 	at me.maker56.survivalgames.game.phases.VotingPhase.sendVoteMessage(VotingPhase.java:244)
[19:22:58] [Server thread/WARN]: 	at me.maker56.survivalgames.game.phases.VotingPhase.access$2(VotingPhase.java:236)
[19:22:58] [Server thread/WARN]: 	at me.maker56.survivalgames.game.phases.VotingPhase$1.run(VotingPhase.java:97)
[19:22:58] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[19:22:58] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349)
[19:22:58] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:781)
[19:22:58] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[19:22:58] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[19:22:58] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[19:22:58] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by andris155** [comment]
Ideiglenes megoldás: Csak 1 aréna beállítva.

**Comment by andris155** [comment]
Javítva, és még + 1 aréna beállítva.
